 <link rel="shortcut icon" href="<?php echo base_url(); ?>public/img/ciencias.ico" type="image/x-icon">
<!--Basic Styles-->
<link href="<?php echo base_url(); ?>public/css/bootstrap.css" rel="stylesheet" />
<!-- <link id="bootstrap-rtl-link" href="index.html" rel="stylesheet" /> -->
<link href="<?php echo base_url(); ?>public/css/font-awesome.css" rel="stylesheet" />
<link href="<?php echo base_url(); ?>public/css/weather-icons.min.css" rel="stylesheet" />
<!--Fonts-->
<link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300" rel="stylesheet" type="text/css">
<link href='http://fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>
<!--Beyond styles-->

<link href="<?php echo base_url(); ?>public/css/demo.min.css" rel="stylesheet" />
<link href="<?php echo base_url(); ?>public/css/typicons.min.css" rel="stylesheet" />
<link href="<?php echo base_url(); ?>public/css/animate.min.css" rel="stylesheet" />
<!-- <link id="skin-link" href="index.php" rel="stylesheet" type="text/css" /> -->
<!--Skin Script: Place this script in head to load scripts for skins and rtl support-->




<link href="<?php echo base_url(); ?>public/css/bootstrap-combobox.css" rel="stylesheet" />


<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>public/css/ultimo.css"/>

<link href="<?php echo base_url(); ?>public/css/mediaelementplayer.css" rel="stylesheet" type="text/css">
<!-- <link href="<?php echo base_url(); ?>public/css/style.css" rel="stylesheet" type="text/css"> -->
<link href="<?php echo base_url(); ?>public/css/iconos.css" rel="stylesheet" type="text/css">
<link href="<?php echo base_url(); ?>public/css/prettyPhoto.css" rel="stylesheet" type="text/css">

<!--[if lte IE 8]><link rel="stylesheet" type="text/css" href="css/ie8.css" media="screen" /><![endif]-->
<!-- Color Style -->
<!-- <link class="alt" href="<?php echo base_url(); ?>public/css/color1.css" rel="stylesheet" type="text/css"> -->
<link href="<?php echo base_url(); ?>public/css/style-switcher.css" rel="stylesheet" type="text/css">
<link href="<?php echo base_url(); ?>public/css/font-awesome.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>public/css/ohover.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>public/css/main.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>public/css/jquery-ui.css"/>



<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>public/css/eventos.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>public/css/actividades.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>public/css/nosotros.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>public/css/multimedia.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>public/css/noti.css"/>



<link href="<?php echo base_url(); ?>public/css/menu.css" rel="stylesheet" />
<link href="<?php echo base_url(); ?>public/css/bootstrap.css" rel="stylesheet" type="text/css">
<!--
<link id="beyond-link" href="<?php echo base_url(); ?>public/css/beyond.min.css" rel="stylesheet" type="text/css" /> -->

<link href="<?php echo base_url(); ?>public/css/jquery.dataTables.css" rel="stylesheet" />
<link href="<?php echo base_url(); ?>public/css/style.css" rel="stylesheet" type="text/css">

<link id="beyond-link" href="<?php echo base_url(); ?>public/css/beyond.min.css" rel="stylesheet" type="text/css" />

<link class="alt" href="<?php echo base_url(); ?>public/css/color1.css" rel="stylesheet" type="text/css">
<link href="<?php echo base_url(); ?>public/css/menu.css" rel="stylesheet" />
<script src="<?php echo base_url(); ?>public/js/validCampo.js"></script>