 <link rel="shortcut icon" href="<?php echo base_url(); ?>public/img/ciencias.ico" type="image/x-icon">


<script src="<?php echo base_url(); ?>public/js/validCampo.js"></script>

<link href="<?php echo base_url(); ?>public/css/bootstrap.css" rel="stylesheet" type="text/css">
<link href="<?php echo base_url(); ?>public/css/style.css" rel="stylesheet" type="text/css">
<link href="<?php echo base_url(); ?>public/css/iconos.css" rel="stylesheet" type="text/css">

<!-- Color Style -->
<link class="alt" href="<?php echo base_url(); ?>public/css/color1.css" rel="stylesheet" type="text/css">
<link href="<?php echo base_url(); ?>public/css/font-awesome.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>public/css/ohover.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>public/css/main.css"/>


<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>public/css/jquery-ui.css"/>

<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>public/css/menu.css"/>


<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>public/css/ultimo.css"/>

<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>public/css/eventos.css"/>

<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>public/css/actividades.css"/>



<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>public/css/animate.css"/>






