

<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" />

<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300" />


<link rel="stylesheet" href="<?php echo base_url(); ?>public/css/bootstrap.min.css" />

<link rel="stylesheet" href="<?php echo base_url(); ?>public/css/ace.min.css" class="ace-main-stylesheet" id="main-ace-style" />


<link href="<?php echo base_url(); ?>public/css/menu.css" rel="stylesheet" />

<link href="<?php echo base_url(); ?>public/css/jquery.dataTables.css" rel="stylesheet" />
