    <!--Basic Scripts-->
    <script src="<?php echo base_url(); ?>public/js/jquery.min.js"></script>
    <script src="<?php echo base_url(); ?>public/js/bootstrap.min.js"></script>
    <script src="<?php echo base_url(); ?>public/js/slimscroll/jquery.slimscroll.min.js"></script>

    <!--Beyond Scripts-->
    <script src="<?php echo base_url(); ?>public/js/beyond.js"></script>


    <!--Page Related Scripts-->
    <!--Sparkline Charts Needed Scripts-->
    <script src="<?php echo base_url(); ?>public/js/charts/sparkline/jquery.sparkline.js"></script>
    <script src="<?php echo base_url(); ?>public/js/charts/sparkline/sparkline-init.js"></script>

    <!--Easy Pie Charts Needed Scripts-->
    <script src="<?php echo base_url(); ?>public/js/charts/easypiechart/jquery.easypiechart.js"></script>
    <script src="<?php echo base_url(); ?>public/js/charts/easypiechart/easypiechart-init.js"></script>

    <!--Flot Charts Needed Scripts-->
    <script src="<?php echo base_url(); ?>public/js/charts/flot/jquery.flot.js"></script>
    <script src="<?php echo base_url(); ?>public/js/charts/flot/jquery.flot.resize.js"></script>
    <script src="<?php echo base_url(); ?>public/js/charts/flot/jquery.flot.pie.js"></script>
    <script src="<?php echo base_url(); ?>public/js/charts/flot/jquery.flot.tooltip.js"></script>

    <script src="<?php echo base_url(); ?>public/js/charts/flot/jquery.flot.orderBars.js"></script>




     <script src="<?php echo base_url(); ?>public/js/jquery.js"></script> <!-- Jquery Library Call -->

       <script src="<?php echo base_url(); ?>public/js/jquery-ui.js"></script> <!-- Jquery Library Call -->
 <script src="<?php echo base_url(); ?>public/js/ultimo.js"></script>
<script src="<?php echo base_url(); ?>public/js/prettyphoto.js"></script> <!-- PrettyPhoto Plugin -->
<script src="<?php echo base_url(); ?>public/js/helper-plugins.js"></script> <!-- Plugins -->
<script src="<?php echo base_url(); ?>public/js/bootstrap.js"></script> <!-- UI -->
<script src="<?php echo base_url(); ?>public/js/waypoints.js"></script> <!-- Waypoints -->
<script src="<?php echo base_url(); ?>public/js/mediaelement-and-player.min.js"></script> <!-- MediaElements -->
<script src="<?php echo base_url(); ?>public/js/init.js"></script> <!-- All Scripts -->
<script src="<?php echo base_url(); ?>public/js/jquery.flexslider.js"></script> <!-- FlexSlider -->
<script src="<?php echo base_url(); ?>public/js/jquery.countdown.min.js"></script> <!-- Jquery Timer -->
<script src="<?php echo base_url(); ?>public/js/jquery_cookie.js"></script>
<script src="<?php echo base_url(); ?>public/js/script.js"></script>

<script src="<?php echo base_url(); ?>public/js/noti.js"></script>

        <script src="<?php echo base_url(); ?>public/js/bootstrap-combobox.js"></script>
    <script src="<?php echo base_url(); ?>public/js/jquery.dataTables.min.js"></script>