




<!-- ultimo avanza del portal de chanis blin -->

<!--[if !IE]> -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

<!-- <![endif]-->

<!--[if IE]>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<![endif]-->

<!--[if !IE]> -->
<script type="text/javascript">
window.jQuery || document.write("<script src='<?php echo base_url(); ?>public/js/jquery.min.js'>"+"<"+"/script>");
</script>

<!-- <![endif]-->

<!--[if IE]>
<script type="text/javascript">
window.jQuery || document.write("<script src='dist/js/jquery1x.min.js'>"+"<"+"/script>");
</script>
<![endif]-->
<script type="text/javascript">
if('ontouchstart' in document.documentElement) document.write("<script src='<?php echo base_url(); ?>public/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
</script>



<!--[if lte IE 8]>
<script src="dist/js/excanvas.min.js"></script>
<![endif]-->
    <script src="<?php echo base_url(); ?>public/js/jquery.min.js"></script>


 <script src="<?php echo base_url(); ?>public/js/bootstrap.min.js"></script>

<script src="<?php echo base_url(); ?>public/js/jquery-ui.custom.min.js"></script>
<script src="<?php echo base_url(); ?>public/js/jquery.ui.touch-punch.min.js"></script>
<script src="<?php echo base_url(); ?>public/js/jquery.easypiechart.min.js"></script>
<script src="<?php echo base_url(); ?>public/js/jquery.sparkline.min.js"></script>
<script src="<?php echo base_url(); ?>public/js/jquery.flot.min.js"></script>
<script src="<?php echo base_url(); ?>public/js/jquery.flot.pie.min.js"></script>
<script src="<?php echo base_url(); ?>public/js/jquery.flot.resize.min.js"></script>

<!-- ace scripts -->
<script src="<?php echo base_url(); ?>public/js/ace-elements.min.js"></script>
<script src="<?php echo base_url(); ?>public/js/ace.min.js"></script>

<script src="<?php echo base_url(); ?>public/js/bootstrap-combobox.js"></script>

<script src="<?php echo base_url(); ?>public/js/ace-extra.min.js"></script>

<script src="<?php echo base_url(); ?>public/js/jquery.dataTables.min.js"></script>