<ul class="nav sidebar-menu">
    <li>
        <a href="" class="menu-dropdown">
            <i class="menu-icon fa fa-cogs"></i>
            <span class="menu-text"> MANTENIMIENTO </span>
            <i class="menu-expand"></i>
        </a>
        <ul class="submenu">
            <li><a href="<?php echo base_url(); ?>Area_c"><span class="menu-text">AREA</span></a></li>
            <li><a href="<?php echo base_url(); ?>Criterio_c"><span class="menu-text">CRITERIO DE EVALUACION</span></a></li>
            <li><a href="<?php echo base_url(); ?>Grado_c"><span class="menu-text">GRADO</span></a></li>
            <li><a href="<?php echo base_url(); ?>Seccion_c"><span class="menu-text">SECCION</span></a></li>
            <li><a href="<?php echo base_url(); ?>Nivel_c"><span class="menu-text">NIVEL</span></a></li>
            <li><a href="<?php echo base_url(); ?>Turno_c"><span class="menu-text">TURNO</span></a></li>
            <li><a href="<?php echo base_url(); ?>Cargo_c"><span class="menu-text">CARGO</span></a></li>
            <li><a href="<?php echo base_url(); ?>TipoD_c"><span class="menu-text">TIPO DISCAPACIDAD</span></a></li>
            <li><a href="<?php echo base_url(); ?>Aspectos_c"><span class="menu-text">ASPECTOS</span></a></li>
            <li><a href="<?php echo base_url(); ?>Actividad_c"><span class="menu-text">ACTIVIDAD</span></a></li>
            <li><a href="<?php echo base_url(); ?>Instruccion_c"><span class="menu-text">GRADO DE INSTRUCCION</span></a></li>
            <li><a href="<?php echo base_url(); ?>Situacion_c"><span class="menu-text">SITUACION LABORAL</span></a></li>
            <li><a href="<?php echo base_url(); ?>TipoDoc_c"><span class="menu-text">TIPO DE DOCUMENTO</span></a></li>
            <li><a href="<?php echo base_url(); ?>TipoS_c"><span class="menu-text">TIPO DE SANGRE</span></a></li>
            <li><a href="<?php echo base_url(); ?>Vacuna_c"><span class="menu-text">VACUNA</span></a></li>
            <li><a href="<?php echo base_url(); ?>Periodo_c"><span class="menu-text">PERIODO</span></a></li>
            <li><a href="<?php echo base_url(); ?>Concepto_c"><span class="menu-text">CONCEPTOS</span></a></li>
        </ul>
    </li>
    <li>
        <a href="" class="menu-dropdown">
            <i class="menu-icon fa fa-book"></i>
            <span class="menu-text"> MATRICULA </span>
            <i class="menu-expand"></i>
        </a>
        <ul class="submenu">
             <li><a href="<?php echo base_url(); ?>RegAlumno_c"><span class="menu-text">REG. ALUMNO</span></a></li>
             <li><a href="#"><span class="menu-text">OTRO CONTROLES</span></a></li>
             <li><a href="#"><span class="menu-text">CONTROL DE PESO y T.</span></a></li>
             <li><a href="#"><span class="menu-text">TRASLADOS</span></a></li>
             <li><a href="#"><span class="menu-text">FAMILIAR</span></a></li>
             <li><a href="#"> <span class="menu-text">DOMICILIO DEL ALUMNO</span></a> </li>
             <li><a href="#"><span class="menu-text">ESTADO DE SALUD</span></a></li>
             <li><a href="#"><span class="menu-text">SITUACION LABORAL</span></a></li>
             <li><a href="#"> <span class="menu-text">OCUPACION</span></a></li>
             <li><a href="<?php echo base_url(); ?>Matricula_c"><span class="menu-text">MATRICULA</span></a></li>
        </ul>
    </li>
    <!--Widgets-->
    <li>
        <a href="" class="menu-dropdown">
            <i class="menu-icon fa fa-pencil"></i>
            <span class="menu-text"> ACADEMICA </span>
            <i class="menu-expand"></i>
        </a>
        <ul class="submenu">
            <li><a href="<?php echo base_url(); ?>Nota_c"><span class="menu-text">NOTAS</span></a></li>
            <li><a href="<?php echo base_url(); ?>Anio_lectivo_c"><span class="menu-text">AÑO LECTIVO</span></a></li>
        </ul>
    </li>
    <li>
        <a href="" class="menu-dropdown">
            <i class="menu-icon fa fa-calculator"></i>
            <span class="menu-text"> PENSIONES </span>
            <i class="menu-expand"></i>
        </a>
        <ul class="submenu">
            <li><a href="<?php echo base_url(); ?>Cuota_c"><span class="menu-text">Cronograma de Cobros</span></a></li>
            <li><a href="<?php echo base_url(); ?>Caja_c"><span class="menu-text">Caja</span></a></li>
            <li><a href="<?php echo base_url(); ?>Movimiento_c"><span class="menu-text">Movimientos</span></a></li>
        </ul>
    </li>
    <li>
        <a href="" class="menu-dropdown">
            <i class="menu-icon fa fa-calendar"></i>
            <span class="menu-text"> ASISTENCIA </span>
            <i class="menu-expand"></i>
        </a>
        <ul class="submenu">
            <li><a href="<?php echo base_url(); ?>Horario_c"><span class="menu-text">Reg. Horario</span></a></li>
            <li><a href="#"><span class="menu-text">Reg. Asistencia</span></a></li>
        </ul>
    </li>
    <li>
        <a href="" class="menu-dropdown">
            <i class="menu-icon fa fa-folder"></i>
            <span class="menu-text"> REPORTES </span>
            <i class="menu-expand"></i>
        </a>
        <ul class="submenu">
            <li><a href="#"><span class="menu-text">Rep. de A. Matriculados</span></a></li>
            <li><a href="#"><span class="menu-text">Rep. Pagos</span></a></li>
            <li><a href="#"><span class="menu-text">Rep. de Calf. por Alumno</span></a></li>
            <li><a href="#"><span class="menu-text">Rep. de Asistencias</span></a></li>
            <li><a href="#"><span class="menu-text">Rep. de Tutor por Seccion</span></a></li>
            <li> <a href="#"><span class="menu-text">Rep. de Traslados por Año</span></a></li>

        </ul>
    </li>

    <li>
        <a href="" class="menu-dropdown">
            <i class="menu-icon fa fa-lock"></i>
            <span class="menu-text"> SEGURIDAD </span>
            <i class="menu-expand"></i>
        </a>
        <ul class="submenu">
            <li><a href="#"><span class="menu-text">PERSONAL</span></a></li>
            <li><a href="#"><span class="menu-text">USUARIOS</span></a></li>
            <li><a href="#"><span class="menu-text">PERMISOS</span></a></li>
            <li><a href="#"><span class="menu-text">TIPO PERSONAL</span></a></li>
            <li><a href="#"><span class="menu-text">PERFIL</span></a></li>
            <li> <a href="#"><span class="menu-text">MODULOS</span></a></li>
            <li> <a href="#"><span class="menu-text">BASE DE DATOS</span></a></li>
        </ul>
    </li>
    <li>
        <a href="" class="menu-dropdown">
            <i class="menu-icon fa fa-globe"></i>
            <span class="menu-text"> PORTAL WEB </span>
            <i class="menu-expand"></i>
        </a>
        <ul class="submenu">
            <li><a href="#"><span class="menu-text">Rep. de A. Matriculados</span></a></li>
            <li><a href="#"><span class="menu-text">Rep. Pagos</span></a></li>
            <li><a href="#"><span class="menu-text">Rep. de Calf. por Alumno</span></a></li>
            <li><a href="#"><span class="menu-text">Rep. de Asistencias</span></a></li>
            <li><a href="#"><span class="menu-text">Rep. de Tutor por Seccion</span></a></li>
            <li> <a href="#"><span class="menu-text">Rep. de Traslados por Año</span></a></li>

        </ul>
    </li>

</ul>